### ISSUE TITLE
Release feature TODO List

### ISSUE THREAD

**Issue by Candygoblen123** [LiveTL/apple#2]
Things that should be implemented before a beta release:
- [ ] Fix chat ordering
- [ ] Timed Chat Messages
- [ ] Translation language setting
- [ ] Allow/deny listing chat authors
- [ ] Trimmed TL messages
- [ ] Investigate archives not finding continuation sometimes
- [ ] Ensure things are destroyed properly on navigation (i.e. stream doesn't keep playing + chat)
- [ ] Ignore old messages (i.e. superchats) when seeking in archives
- [ ] Handle seeking/pausing for chat better in general for archives

Nice to haves:
- [ ] New member messages
- [ ] Better timestamp format
- [ ] Long-press stream info on home page list
- [ ] About page info (including OSS licenses)
- [ ] Ability to choose All Chats instead of Top Chats
- [ ] Superstickers

**Comment by GrumpyBear57** [comment]
Just a note to check to make sure that all the items apply to this repo, or haven't already been implemented fixed

i.e.
> Investigate archives not finding continuation sometimes

Is probably specific to Android, and has no relation here
